"""Exercise the installed Endless extension without a server or game.
Usage: python Tools/test_endless_mode.py --archipelago PATH --run-json RUN_JSON
The run JSON is generated by SlayTheStarCraft.py; test saves use a temporary directory.
"""
from pathlib import Path
from types import SimpleNamespace
import argparse,copy,json,os,sys,tempfile
parser=argparse.ArgumentParser()
parser.add_argument('--archipelago',required=True,type=Path)
parser.add_argument('--run-json',required=True,type=Path)
args=parser.parse_args()
os.environ['SKIP_REQUIREMENTS_UPDATE']='1'
TEST=Path(tempfile.mkdtemp(prefix='slay-endless-test-'))
os.environ['SLAY_RUN_DIR']=str(TEST)
sys.path.insert(0,str(args.archipelago.resolve()))
from worlds.sc2 import slay_the_starcraft as s
from worlds.sc2.client import SC2Context,ArchipelagoBot
from SlayTheStarCraft import generate_endless_layer,endless_map_key
raw=json.loads(args.run_json.read_text(encoding='utf-8'))
raw['game_mode']='endless'
ctx=SimpleNamespace(slay_config=s._normalize_config(raw),slay_state=copy.deepcopy(s.DEFAULT_STATE),slay_state_loaded=True,items_received=[],checked_locations=set(),missing_locations=set(),mission_id_to_location_ids={},ui=None,finished_game=False)
ctx.is_mission_completed=lambda mid:SC2Context.is_mission_completed(ctx,mid)
progress={'floor':0,'choices':[],'history':[],'offers':[],'selected':None}
s._new_endless_floor(ctx,progress)
ctx.slay_state['endless']=progress
recent=[]
last_base=0
repeated=0
for floor in range(120):
 progress=s.state(ctx)['endless']
 offers=progress['choices']
 keys=[endless_map_key(n) for n in offers]
 assert len(set(keys))==len(offers) and 2<=len(offers)<=4
 assert not (set(keys)&{k for offer in recent[-4:] for k in offer})
 recent.append(keys)
 assert sum(not n['high_risk'] for n in offers)>=1
 assert s.edge_pairs(ctx)==[] and s.traversed_edge_pairs(ctx)==[]
 assert len(s.current_frontier(ctx))==len(offers)
 pass
 mid=offers[floor%len(offers)]['mission_id']
 before=s.credits(ctx)
 assert s.commit_mission(ctx,mid)
 assert s.current_frontier(ctx)==[mid]
 assert not s.commit_mission(ctx,next(n['mission_id'] for n in offers if n['mission_id']!=mid))
 reward=s.node(ctx,mid)['credit_reward']
 selected=copy.deepcopy(s.state(ctx))
 ctx.slay_state=s._sanitize_state(selected)
 assert s.state(ctx)['endless']['selected']==mid
 assert s.complete_endless_mission(ctx,mid,floor)
 assert not s.complete_endless_mission(ctx,mid,floor)
 assert s.victory_count(ctx)==floor+1
 assert len(s.completed_mission_ids(ctx))==floor+1
 assert s.credits(ctx)==before+reward
 restored=s._sanitize_state(json.loads((TEST/'slay_state.json').read_text()))
 assert restored['endless']==s.state(ctx)['endless']
 ctx.slay_state=restored
 # Re-generation uses the original seed and the four preceding floors deterministically.
 copy_progress=copy.deepcopy(progress);copy_progress['offers']=recent[:-1][-4:]
 assert generate_endless_layer(ctx.slay_config,copy_progress)==offers
# Native bot carries the round token, so late duplicate callbacks cannot complete another floor.
ctx.last_bot=None
bot=ArchipelagoBot(ctx,s.current_frontier(ctx)[0])
assert bot.slay_floor_token==120
assert bot.missions_beaten_count()==120
# Adventure mode keeps the existing save defaults and graph.
ctx.slay_config['game_mode']='adventure';ctx.slay_state=copy.deepcopy(s.DEFAULT_STATE)
ctx.is_mission_completed=lambda mid:False
assert not s.endless_mode(ctx)
assert len(s.nodes(ctx))==len(raw['nodes'])
assert s._sanitize_state({'spent':7})['spent']==7
assert 'endless' not in s._sanitize_state({'spent':7})
report={'floors_tested':120,'five_floor_exclusion_includes_all_offers':True,'same_map_other_races_count_as_repeat':True,'victory_idempotent':True,'native_save_reload':True,'adventure_unchanged':True,'no_game_launched':True}
import shutil
shutil.rmtree(TEST)
print(json.dumps(report,ensure_ascii=False),flush=True)
